### ISSUE TITLE
Error: Environment key "es2021" is unknown

### ISSUE THREAD

**Issue by EvgenyOrekhov** [NullVoxPopuli/eslint-plugin-decorator-position#138]
I'm using the new `es2021` environment in my `.eslintrc.json` introduced in ESLint 7.8.0:

```json
{
  "env": { "es2021": true },
  "plugins": ["decorator-position"],
  "rules": {
    "decorator-position/decorator-position": "error"
  }
}
```

And eslint-plugin-decorator-position throws the following error:

```text
Error: Error while loading rule 'decorator-position/decorator-position': .eslintrc.json » ./index.json » eslint-config-hardcore » ./base.json:
        Environment key "es2021" is unknown

Occurred while linting .eslintrc.json
    at node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\shared\config-validator.js:163:19
    at Array.forEach (<anonymous>)
    at validateEnvironment (node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\shared\config-validator.js:157:30)
    at validateConfigArray (node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\shared\config-validator.js:309:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:464:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:275:21)
    at CLIEngine.getConfigForFile (node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\cli-engine\cli-engine.js:933:14)
    at lineLength (node_modules\eslint-plugin-decorator-position\lib\rules\decorator-position.js:327:35)
    at Object.decoratorPositionRule [as create] (node_modules\eslint-plugin-decorator-position\lib\rules\decorator-position.js:138:27)
    at createRuleListeners (node_modules\eslint\lib\linter\linter.js:761:21)
```

eslint-plugin-decorator-position: 2.2.1
ESLint: 7.8.0

**Comment by NullVoxPopuli** [comment]
I think this is supposed to be a parserOption, rather than an env:

```
"parserOptions": {
  "ecmaVersion": 2021
},
```

**Comment by EvgenyOrekhov** [comment]
@NullVoxPopuli Nope, you can have either. From the [Specifying Environments](https://eslint.org/docs/user-guide/configuring#specifying-environments) section of the docs:

> `es2021` - adds all ECMAScript 2021 globals and automatically sets the `ecmaVersion` parser option to 12

I even argue that it is better to always use `env` instead of `parserOptions`, because an env also adds the corresponding globals.

**Comment by NullVoxPopuli** [comment]
Your stock trace is:

```
Occurred while linting .eslintrc.json
    at node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\shared\config-validator.js:163:19
```

So that tells me that something is wrong with a configif you remove the decorator position stuff from your config, do you still got the error?

**Comment by EvgenyOrekhov** [comment]
That's actually not a problem with `.eslintrc.json`, it's just I'm using [eslint-plugin-json](https://github.com/azeemba/eslint-plugin-json) for linting `*.json` files, and `.eslintrc.json` happens to be the first file.

If I remove eslint-plugin-decorator-position from my config, the problem goes away, so it's definitely has something to do with eslint-plugin-decorator-position.

**Comment by EvgenyOrekhov** [comment]
Minimal reproducible case:

```json
{
  "env": { "es2021": true },
  "plugins": ["decorator-position"],
  "rules": {
    "decorator-position/decorator-position": "error"
  }
}
```

**Comment by NullVoxPopuli** [comment]
Thanks! Now all we need is a failing test case

**Comment by EvgenyOrekhov** [comment]
@NullVoxPopuli I tried to create a failing test case, but I couldn't reproduce it on `master`. But I think I figured it out.

eslint-plugin-decorator-position **2.2.1** only supports ESLint **7.3.1**: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/v2.2.1/package.json#L91. You can see in my stack trace that the plugin uses its own version of ESLint, not the top-level one:

```
node_modules\eslint-plugin-decorator-position\node_modules\eslint\lib\shared\config-validator.js
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It should be

```
node_modules\eslint\lib\shared\config-validator.js
```

I can see in the latest `master` that you already have ESLint 7.9.0: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/master/package.json#L91.

So, in order to fix this you just need to publish a new release.

Also, in order to prevent this kind of breakages in the future, you should use a version range instead of an exact version, e. g. `"eslint": "^7.9.0"`.

**Comment by NullVoxPopuli** [comment]
Good catch!

I need to update the renovate config to be looser on package.jsos updates

**Comment by EvgenyOrekhov** [comment]
@NullVoxPopuli Any progress on this?

**Comment by NullVoxPopuli** [comment]
sorry, I've been busy/stressed. PRs welcome. Gonna make this count for hacktoberfest if you want

**Comment by EvgenyOrekhov** [comment]
@NullVoxPopuli This one can only be fixed by **publishing a new release**. Or do you mean you want a PR for fine-tuning Renovate Bot config? Unfortunately, I'm not familiar with it.

**Comment by NullVoxPopuli** [comment]
You Got it! Publishing is automated after PR merge

**Comment by maxizhukov** [comment]
Hi) I installed version "eslint-plugin-decorator-position": "^2.2.2", but still have the same earning : 
Environment key "es2021" is unknown
`{
    "env": {
        "browser": true,
        "es2021": true
    },
    "plugins": [
        "react",
        "@typescript-eslint",
        "decorator-position"

    ],
    "parser": "@typescript-eslint/parser",
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:decorator-position/ember"
    ],
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 2018,
        "sourceType": "module"
    },`

**Comment by NullVoxPopuli** [comment]
@maxizhukov can you open a new issue? 

I made this: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/pull/176
and was unable to reproduce.

if you open a new issue, let's discuss details about your setup / configuration / versions over there.

Thanks!

**Comment by maxizhukov** [comment]
@NullVoxPopuli I installed version 2.2.3
But have the same problem((
`Error: .eslintrc.json:
	Environment key "es2021" is unknown`

**Comment by NullVoxPopuli** [comment]
Based off the example in #176, can you submit a reproduction PR?

**Comment by db306** [comment]
FYI I just bumped into this, I have the same issue and I don't have **eslint-plugin-decorator-position** @maxizhukov I think this could come from somewhere else

**Comment by lexjacobs** [comment]
I found success by leaving this as is:
```
  env: {
    'es6': true
  },
```

and changing the ecmaVersion value from 6 to 8 here:
```
  parserOptions: {
    sourceType: 'module',
    ecmaVersion: 8,
    ecmaFeatures: {
      'jsx': true
    }
  },
```

**Comment by vuggy17** [comment]
> Hi) I installed version "eslint-plugin-decorator-position": "^2.2.2", but still have the same earning :
> Environment key "es2021" is unknown
> `{
> "env": {
> "browser": true,
> "es2021": true
> },
> "plugins": [
> "react",
> "@typescript-eslint",
> "decorator-position"
> 
> ```
> ],
> "parser": "@typescript-eslint/parser",
> "extends": [
>     "eslint:recommended",
>     "plugin:react/recommended",
>     "plugin:@typescript-eslint/recommended",
>     "plugin:decorator-position/ember"
> ],
> "parserOptions": {
>     "ecmaFeatures": {
>         "jsx": true
>     },
>     "ecmaVersion": 2018,
>     "sourceType": "module"
> },`
> ```
I solve this by update react-script version to 4.0.3 and react to 17.0.2

**Comment by Desarrollos-Web-Urquiza** [comment]
> FYI I just bumped into this, I have the same issue and I don't have **eslint-plugin-decorator-position** @maxizhukov I think this could come from somewhere else.
> 
> When running `npx eslint --version`, make sure you have at least version 7.8.0 I had version 5.16.0 and updating to 7.14 fixed this for me.

For update to the latest eslint version, you can change the version from the `package.json` to `"eslint": "^7.8.0"` and run npm install

**Comment by TudorPetrariu** [comment]
You need to update your ESLint then, es2021 was introduced in ESLint version 7.8.0: https://github.com/eslint/eslint/releases/tag/v7.8.0

**Comment by dark-kitt** [comment]
I had the same issue with eslint v8.23.0 switching back to v8.22.0 solved the problem.
